## 应用名称
#spring.application.name=gameWeb
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-vo=com.xiaoze.gameweb.mybatis.entity
## 数据源名称
#spring.datasource.name=defaultDataSource

# 应用服务 WEB 访问端口
server:
  port: 8958
spring:
  # 应用名称
  application:
    name: ReservationSystem
  # 配置数据库连接信息
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.140.198.220:3306/api_ezeat_com?serverTimezone=UTC&characterEncoding=utf-8&userssl=false
      username: root
      password: ezeat1823mysql-
  # 关闭日志图标
  main:
    banner-mode: off
  # 配置跳转页面前后缀
  mvc:
    view:
      prefix:
      suffix:
  #自定义日期格式
  jackson:
    date-format: yyyy-MM-dd


# mybatis配置信息
mybatis-plus:
  global-config:
    db-config:
      # table-prefix: ezeat_
      id-type: auto
    # 关闭日志图标
    banner: off

